/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
    useMutation,
    useQuery
} from '@tanstack/react-query'
import type {
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    QueryKey
} from '@tanstack/react-query'
import type { AxiosResponse } from 'axios'
import { customInstance } from './axios'

export type ValidationError = {
    loc: (string | number)[];
    msg: string;
    type: string;
};

export type HTTPValidationError = {
    detail?: ValidationError[];
};

export type PredictionRequest = {
    /** Patient Name */
    patient_name: string;
    /** Age */
    age: number;
    /**
     * Liters
     * @minimum 0.5
     * @maximum 8
     */
    fev1: number;
    /**
     * L/min
     * @minimum 50
     * @maximum 700
     */
    pef: number;
    /**
     * Percentage
     * @minimum 70
     * @maximum 100
     */
    spo2: number;
    /**
     * Zip Code
     * @pattern ^\d{6}$
     */
    zip_code: string;
    /** Gender */
    gender: string;
    /** Smoking Status */
    smoking: string;
    /** Height (cm) */
    height?: number;
    /** Weight (kg) */
    weight?: number;
    /** Wheezing */
    wheezing: boolean;
    /** Shortness of Breath */
    shortness_of_breath: boolean;
    /** Medication Use */
    medication_use: boolean;
    /** Patient ID */
    patient_id?: string;
};

export type PredictionInterval = {
    lower_bound: number;
    upper_bound: number;
};

export type TrustSignal = {
    trust_rating: 'high' | 'medium' | 'low';
    prediction_interval: PredictionInterval;
};

export type Prediction = {
    risk_score: number;
};

export type EnvironmentalData = {
    aqi: number;
    pm25: number;
    temperature: number;
    humidity: number;
    source: string;
};

export type AnomalyDetection = {
    is_outlier: boolean;
    anomaly_score: number;
    flagged_features: string[];
};

export type PredictionResponse = {
    prediction: Prediction;
    trust_signal: TrustSignal;
    environmental_data: EnvironmentalData;
    anomaly_detection: AnomalyDetection;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = (

) => {

    return customInstance<unknown>(
        {
            url: `/health`, method: 'GET'
        },
    );
}


export const getHealthCheckHealthGetQueryKey = () => {
    return [`/health`] as const;
}


export const useHealthCheckHealthGet = <TData = AxiosResponse<unknown>, TError = unknown>(
    options?: { query?: UseQueryOptions<TData, TError, TData, QueryKey> }

): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

    const queryOptions = getHealthCheckHealthGetQueryKey()

    const query = useQuery({
        queryKey: queryOptions,
        queryFn: () => healthCheckHealthGet() as Promise<TData>,
        ...options?.query,
    })

    return {
        ...query,
        queryKey: queryOptions,
    }
}

/**
 * Predict Risk
 */
export const predictRiskPredictPost = (
    predictionRequest: PredictionRequest,
) => {

    return customInstance<PredictionResponse>(
        {
            url: `/predict`, method: 'POST',
            headers: { 'Content-Type': 'application/json', },
            data: predictionRequest
        },
    );
}



export const usePredictRiskPredictPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?: UseMutationOptions<AxiosResponse<PredictionResponse>, TError, { data: PredictionRequest }, TContext> }
    ): UseMutationResult<AxiosResponse<PredictionResponse>, TError, { data: PredictionRequest }, TContext> => {

    const mutationOptions = {
        mutationFn: ({ data }: { data: PredictionRequest }) => {
            return predictRiskPredictPost(data)
        },
        ...options?.mutation,
    }


    return useMutation(mutationOptions)
}

export type ExplanationRequest = {
    query: string;
    features: Record<string, unknown>;
    risk_score: number;
};

export type ExplanationResponse = {
    text: string;
};

/**
 * @summary Explain Risk
 */
export const explainRisk = (
    explanationRequest: ExplanationRequest,
) => {
    return customInstance<ExplanationResponse>(
        {
            url: `/explain`, method: 'POST',
            headers: { 'Content-Type': 'application/json', },
            data: explanationRequest
        });
}


/**
 * Get History
 */
export type PredictionRecord = {
    id: string;
    created_at: string;
    patient_name?: string; // Optional for backward compatibility
    age: number;
    fev1: number;
    pef: number;
    spo2: number;
    zip_code: string;
    risk_score: number;
    uncertainty: number;
    trust_rating: 'high' | 'medium' | 'low';
    gender?: string;
    smoking?: string;
    wheezing?: boolean;
    shortness_of_breath?: boolean;
    bmi?: number;
    medication_use?: boolean;
}

export const getHistoryGet = () => {
    return customInstance<PredictionRecord[]>({
        url: `/history`, method: 'GET'
    });
}

export const getHistoryGetQueryKey = () => {
    return [`/history`] as const;
}

export const useHistoryGet = <TData = AxiosResponse<PredictionRecord[]>, TError = unknown>(
    options?: { query?: UseQueryOptions<TData, TError, TData, QueryKey> }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

    const queryOptions = getHistoryGetQueryKey()

    const query = useQuery({
        queryKey: queryOptions,
        queryFn: () => getHistoryGet() as Promise<TData>,
        ...options?.query,
    })

    return {
        ...query,
        queryKey: queryOptions,
    }
}
export type StatsResponse = {
    total_patients: number;
    high_risk_count: number;
    avg_fev1: number;
}

export const getStatsGet = () => {
    return customInstance<StatsResponse>({
        url: `/stats`, method: 'GET'
    });
}

export const getStatsGetQueryKey = () => {
    return [`/stats`] as const;
}

export const useStatsGet = <TData = AxiosResponse<StatsResponse>, TError = unknown>(
    options?: { query?: UseQueryOptions<TData, TError, TData, QueryKey> }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

    const queryOptions = getStatsGetQueryKey()

    const query = useQuery({
        queryKey: queryOptions,
        queryFn: () => getStatsGet() as Promise<TData>,
        ...options?.query,
    })

    return {
        ...query,
        queryKey: queryOptions,
    }
}
